name: Build and release
on:
  push:
jobs:
  build-project:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]
    name: Build Project
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      # - name: Setup Ninja
      #   uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: source
          build-dir: output
          generator: Ninja
          cxx-compiler: clang++
