name: Build and release
on:
  push:
jobs:
  build-project:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-13, macos-14, windows-2022]
    name: Build Project
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Wayland
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install libwayland-dev

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: .build
          generator: Ninja
          # c-compiler: clang
          # cxx-compiler: clang++
